package com.forraje.igu;

import com.forraje.logica.Registro;
import com.forraje.persistencia.RegistroData;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.TextStyle;
import java.time.temporal.WeekFields;
import java.util.Date;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author dannita
 */
public class JDialogRecord extends javax.swing.JDialog {
    public RegistroData rd;

    /**
     * Creates new form JDialogRecord
     */
    public JDialogRecord(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rd = new RegistroData();
        Date date = fechaDefecto();
        fillComboBox1();
        fillComboBox2();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldDay = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldWeek = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jComboBoxChooserPay = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDetails = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jCheckBoxEnableDate = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jComboBoxRecordType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldAmount = new javax.swing.JTextField();
        jComboBoxRecord = new javax.swing.JComboBox<>();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nuevo registro");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 370, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Fecha:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, -1));

        jDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser.setForeground(new java.awt.Color(0, 0, 0));
        jDateChooser.setEnabled(false);
        jDateChooser.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jDateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserPropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 120, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Dia:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, -1, -1));

        jTextFieldDay.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTextFieldDay.setEnabled(false);
        jPanel1.add(jTextFieldDay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 120, -1));

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Semana:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        jTextFieldWeek.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTextFieldWeek.setEnabled(false);
        jPanel1.add(jTextFieldWeek, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 120, -1));

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Registro:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, 60, -1));

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Monto:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jComboBoxChooserPay.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxChooserPay.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jComboBoxChooserPay.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxChooserPay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxChooserPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 120, -1));

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Detalles:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, -1, -1));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextAreaDetails.setColumns(20);
        jTextAreaDetails.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTextAreaDetails.setForeground(new java.awt.Color(0, 0, 0));
        jTextAreaDetails.setRows(5);
        jTextAreaDetails.setBorder(null);
        jScrollPane1.setViewportView(jTextAreaDetails);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 170, 50));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jButton1.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Cancelar");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 80, 20));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jButton2.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Guardar");
        jButton2.setBorder(null);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, 80, 20));

        jCheckBoxEnableDate.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jCheckBoxEnableDate.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxEnableDate.setText("Modificar fecha");
        jCheckBoxEnableDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxEnableDateActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBoxEnableDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, -1, -1));

        jLabel8.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Modo de pago:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, -1, -1));

        jComboBoxRecordType.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxRecordType.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jComboBoxRecordType.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxRecordType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBoxRecordType, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 120, -1));

        jLabel9.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Tipo de registro:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        jTextFieldAmount.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jPanel1.add(jTextFieldAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 120, -1));

        jComboBoxRecord.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxRecord.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        jComboBoxRecord.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxRecord.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxRecord.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxRecordItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 120, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxEnableDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxEnableDateActionPerformed
        if (jCheckBoxEnableDate.isSelected()) {
            jDateChooser.setEnabled(true);
        } else {
            jDateChooser.setEnabled(false);
        }
    }//GEN-LAST:event_jCheckBoxEnableDateActionPerformed

    private void jDateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserPropertyChange
        if("date".equals(evt.getPropertyName())) {
            Date date = jDateChooser.getDate();
            diaDefecto(date);
            semanaDefecto(date);
        }
    }//GEN-LAST:event_jDateChooserPropertyChange

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LocalDate date = jDateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String dia = jTextFieldDay.getText();
        int semana = Integer.parseInt(jTextFieldWeek.getText());
        String registro = (String) jComboBoxRecord.getSelectedItem();
        String tipoRegistro = (String) jComboBoxRecordType.getSelectedItem();
        String modoPago = (String) jComboBoxChooserPay.getSelectedItem();
        String detalles = jTextAreaDetails.getText();
        try {
           double monto = Double.parseDouble(jTextFieldAmount.getText());
           boolean flag = rd.crearRegistro(new Registro(date, dia, semana, registro, tipoRegistro, monto, modoPago, detalles));
           if(flag){
               int confirm = JOptionPane.showConfirmDialog(this, "Registro creado con exito! ¿Desea crear otro?", "Success", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
               switch(confirm){
                   case JOptionPane.NO_OPTION:
                       dispose();
                   case JOptionPane.YES_OPTION:
                       jTextFieldAmount.setText(null);
                       break;
               }
           }
        }catch (NumberFormatException nfe){
           JOptionPane.showMessageDialog(this, "Ingrese un monto valido!");
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBoxRecordItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxRecordItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            jComboBoxRecordType.removeAllItems();
            String selec = (String) jComboBoxRecord.getSelectedItem();
            if (selec.equals("Ingreso")) {
                jComboBoxRecordType.addItem("Venta");
                jComboBoxRecordType.addItem("Ajuste/Otro");
                jComboBoxRecordType.addItem("Rendimiento");
            } else if (selec.equals("Egreso")) {
                jComboBoxRecordType.addItem("Compra/Pago");
                jComboBoxRecordType.addItem("Ajuste/Otro");
            }
        }
    }//GEN-LAST:event_jComboBoxRecordItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogRecord dialog = new JDialogRecord(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBoxEnableDate;
    private javax.swing.JComboBox<String> jComboBoxChooserPay;
    private javax.swing.JComboBox<String> jComboBoxRecord;
    private javax.swing.JComboBox<String> jComboBoxRecordType;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaDetails;
    private javax.swing.JTextField jTextFieldAmount;
    private javax.swing.JTextField jTextFieldDay;
    private javax.swing.JTextField jTextFieldWeek;
    // End of variables declaration//GEN-END:variables

    private Date fechaDefecto() {
        LocalDate date = LocalDate.now();
        Date dateDate = java.sql.Date.valueOf(date);
        jDateChooser.setDate(dateDate);
        return dateDate;
    }
    private void diaDefecto(Date date) {
        LocalDate day = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        String dayName = day.getDayOfWeek().getDisplayName(TextStyle.FULL, new Locale("es", "ES"));
        jTextFieldDay.setText(dayName);
    }
    private void semanaDefecto(Date date){
        LocalDate week = date.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
        WeekFields regWeeks = WeekFields.of(Locale.getDefault());
        int weekNumber = week.get(regWeeks.weekOfWeekBasedYear());
        jTextFieldWeek.setText(String.valueOf(weekNumber));
    }
    private void fillComboBox1(){
        jComboBoxRecord.removeAllItems();
        jComboBoxRecord.addItem("Ingreso");
        jComboBoxRecord.addItem("Egreso");
    }
    private void fillComboBox2(){
        jComboBoxChooserPay.removeAllItems();
        jComboBoxChooserPay.addItem("Efectivo");
        jComboBoxChooserPay.addItem("Transferencia");
    }
    
    /*private void fillComboBox3() {
        if (jComboBoxRecord.getSelectedItem().toString().equals("Ingreso")) {
            jComboBoxRecordType.removeAllItems();
            jComboBoxRecordType.addItem("Venta");
            jComboBoxRecordType.addItem("Ajuste/Otro");
            jComboBoxRecordType.addItem("Rendimiento");
        } else if (jComboBoxRecord.getSelectedItem().toString().equals("Egreso")) {
            jComboBoxRecordType.removeAllItems();
            jComboBoxRecordType.addItem("Compra/Pago");
            jComboBoxRecordType.addItem("Ajuste/Otro");
        } else {
            jComboBoxRecordType.removeAllItems();
        }
    }*/
}
