/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package com.forraje.igu;

import com.forraje.logica.Registro;
import com.forraje.persistencia.RegistroData;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;

/**
 *
 * @author dannita
 */
public class JDialogMngIList extends javax.swing.JDialog {

    private RegistroData rd;

    private final DefaultTableModel table = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    /**
     * Creates new form JDialogMngList
     */
    public JDialogMngIList(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        rd = new RegistroData();
        columns();
        componentsInvisibility();
        fillComboBox1();
        fillComboBox2();
        rows(null, 0);
        ((javax.swing.text.JTextComponent) jDateChooser.getDateEditor().getUiComponent()).setEditable(false);
        tablaSizes();
        Dimension screen = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screen);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jPanel4 = new javax.swing.JPanel();
        jButtonModify = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        jPanelBgButton5 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jComboBoxFilters = new javax.swing.JComboBox<>();
        jComboBoxMonths = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jButtonDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de ingresos");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestión de ingresos");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 17, -1, -1));

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Filtrar por:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 60, -1));

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 13)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Fecha:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(88, 90, 40, -1));

        jDateChooser.setBackground(new java.awt.Color(255, 255, 255));
        jDateChooser.setForeground(new java.awt.Color(0, 0, 0));
        jDateChooser.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jDateChooser.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jDateChooserPropertyChange(evt);
            }
        });
        jPanel1.add(jDateChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 120, -1));

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));

        jButtonModify.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jButtonModify.setForeground(new java.awt.Color(255, 255, 255));
        jButtonModify.setText("Modificar registro");
        jButtonModify.setBorder(null);
        jButtonModify.setContentAreaFilled(false);
        jButtonModify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonModify.setFocusPainted(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonModify, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonModify, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 130, 20));

        jTable.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(jTable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 1310, 500));

        jPanelBgButton5.setBackground(new java.awt.Color(0, 0, 0));

        jButton3.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Limpiar fecha");
        jButton3.setBorder(null);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBgButton5Layout = new javax.swing.GroupLayout(jPanelBgButton5);
        jPanelBgButton5.setLayout(jPanelBgButton5Layout);
        jPanelBgButton5Layout.setHorizontalGroup(
            jPanelBgButton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanelBgButton5Layout.setVerticalGroup(
            jPanelBgButton5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBgButton5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanelBgButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 100, 20));

        jComboBoxFilters.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxFilters.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jComboBoxFilters.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxFilters.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxFilters.setBorder(null);
        jComboBoxFilters.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxFiltersItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxFilters, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 110, 20));

        jComboBoxMonths.setBackground(new java.awt.Color(255, 255, 255));
        jComboBoxMonths.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jComboBoxMonths.setForeground(new java.awt.Color(0, 0, 0));
        jComboBoxMonths.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxMonths.setBorder(null);
        jComboBoxMonths.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxMonthsItemStateChanged(evt);
            }
        });
        jPanel1.add(jComboBoxMonths, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 110, 20));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        jButtonDelete.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Eliminar registro");
        jButtonDelete.setBorder(null);
        jButtonDelete.setContentAreaFilled(false);
        jButtonDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDelete.setFocusPainted(false);
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButtonDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 130, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1366, 768));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jDateChooserPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jDateChooserPropertyChange
        if ("date".equals(evt.getPropertyName())) {
            Date selDate = jDateChooser.getDate();
            if (selDate != null) {
                LocalDate date = selDate.toInstant().atZone(ZoneId.systemDefault()).toLocalDate();
                rows(jDateChooser.getDate() == null ? null : jDateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), 0);
            } else {
                rows(null,0);
            }
        }
    }//GEN-LAST:event_jDateChooserPropertyChange

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jDateChooser.setDate(null);
        jComboBoxMonths.setSelectedIndex(0);
        rows(null, 0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBoxMonthsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxMonthsItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            int selec = jComboBoxMonths.getSelectedIndex() + 1;
            rows(jDateChooser.getDate() == null ? null : jDateChooser.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate(), selec);
        }
    }//GEN-LAST:event_jComboBoxMonthsItemStateChanged

    private void jComboBoxFiltersItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxFiltersItemStateChanged
        if (evt.getStateChange() == java.awt.event.ItemEvent.SELECTED) {
            int selec = jComboBoxFilters.getSelectedIndex();
            if (selec == 0) {
                jComboBoxMonths.setVisible(false);
                fieldDateVisibility();
            } else {
                jDateChooser.setVisible(false);
                fieldMonthVisibility();
            }
        }
    }//GEN-LAST:event_jComboBoxFiltersItemStateChanged

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        int selec = jTable.getSelectedRow();
        int id;
        if (selec == -1) {
            JOptionPane.showMessageDialog(this, "Selecciona una fila de la tabla para eliminarla");
            return;
        } else {
            id = (int) jTable.getValueAt(selec, 0);
        }
        if (rd.eliminarRegistro(id)) {
            JOptionPane.showMessageDialog(this, "Registro eliminado exitosamente");
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrió un error inesperado");
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogMngIList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogMngIList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogMngIList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogMngIList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDialogMngIList dialog = new JDialogMngIList(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonModify;
    private javax.swing.JComboBox<String> jComboBoxFilters;
    private javax.swing.JComboBox<String> jComboBoxMonths;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelBgButton5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    // End of variables declaration//GEN-END:variables

    
    private void tablaSizes() {
        TableColumnModel columnModel = jTable.getColumnModel();
        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(5).setPreferredWidth(100);
        columnModel.getColumn(6).setPreferredWidth(80);
        columnModel.getColumn(7).setPreferredWidth(100);
        columnModel.getColumn(8).setPreferredWidth(250);
        jTable.setRowHeight(30);
    }
    
    private void fieldMonthVisibility() {
        jLabel3.setText("Mes:");
        jComboBoxMonths.setVisible(true);
        jPanelBgButton5.setVisible(true);
        jButton3.setVisible(true);
    }
    
    private void fieldDateVisibility() {
        jLabel3.setText("Fecha:");
        jDateChooser.setVisible(true);
        jPanelBgButton5.setVisible(true);
        jButton3.setVisible(true);
    }
    
    private void componentsInvisibility() {
        jComboBoxMonths.setVisible(false);
        jDateChooser.setVisible(false);
        jLabel3.setText(null);
        jPanelBgButton5.setVisible(false);
    }

    private void fillComboBox2() {
        jComboBoxFilters.removeAllItems();
        jComboBoxFilters.addItem("Fecha");
        jComboBoxFilters.addItem("Mes");
    }

    private void fillComboBox1() {
        jComboBoxMonths.removeAllItems();
        jComboBoxMonths.addItem("Enero");
        jComboBoxMonths.addItem("Febrero");
        jComboBoxMonths.addItem("Marzo");
        jComboBoxMonths.addItem("Abril");
        jComboBoxMonths.addItem("Mayo");
        jComboBoxMonths.addItem("Junio");
        jComboBoxMonths.addItem("Julio");
        jComboBoxMonths.addItem("Agosto");
        jComboBoxMonths.addItem("Septiembre");
        jComboBoxMonths.addItem("Octubre");
        jComboBoxMonths.addItem("Noviembre");
        jComboBoxMonths.addItem("Diciembre");
    }

    private void columns() {
        table.addColumn("ID");
        table.addColumn("Fecha");
        table.addColumn("Dia");
        table.addColumn("Semana");
        table.addColumn("Registro");
        table.addColumn("Tipo");
        table.addColumn("Monto");
        table.addColumn("Pago");
        table.addColumn("Detalles");
        jTable.setModel(table);
    }

    private void rows(LocalDate date, int month) {
        table.setRowCount(0);
        List<Registro> list = new ArrayList<>(rd.listarRegistros());
        boolean aux = (date == null);
        boolean aux2 = (month == 0);
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        for (Registro r : list) {
            LocalDate dateParsed = LocalDate.parse(r.getFecha());
            if ((aux || dateParsed.equals(date)) && (aux2 || dateParsed.getMonthValue() == month) && r.getRegistro().equals("Ingreso")) {
                String formatedDate = dateParsed.format(formatter);
                Object[] filas = {
                    r.getId(), formatedDate, r.getDia(), r.getSemana(), r.getRegistro(), r.getTipoRegistro(), r.getMonto(), r.getModoDePago(), r.getDetalles()
                };
                table.addRow(filas);
            }
        }
    }

}
